#!/bin/bash
packaging_path=`pwd`
cd "$packaging_path"
git clone "https://github.com/persepolisdm/persepolis.git" persepolis
python3 pyinstaller/pyinstaller.py persepolis/files/Persepolis\ Download\ Manager -w -i icon.icns
cp aria2c 'persepolis/dist/Persepolis Download Manager.app/Contents/MacOS/'
cp Info.plist 'persepolis/dist/Persepolis Download Manager.app/Contents/'
mv 'persepolis/dist/Persepolis Download Manager.app' .
rm -rf dist
rm -rf build
rm -rf persepolis
rm 'Persepolis Download Manager.spec'
